[package]
name = "async-openai-specgen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
convert_case = "0.8.0"
regex = "1.11.1"
saphyr = "0.0.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
